title:              Poleis. Blog
tagline:            on Cities and Classics
description:        current confusion over everything due to lack of Greek and Latin
url:                http://smitr.github.io

author:
  name:             Your Name
  url:              https://twitter.com/smitrovic
  email:            smitrovic@gmx.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
