title:              Poleis
tagline:            Blog on Cities and Classics
description:        current confusion over everything due to lack of Greek and Latin
url:                https://poleis.co

author:
  name:             Lobo Magarity
  url:              https://twitter.com/smitrovic
  email:            smitrovic@gmx.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
